### ISSUE TITLE
I/O pin kontrollieren für Relais

### ISSUE THREAD

**Issue by sikousikou** [jp112sdl/HB-UNI-Sen-RFID-RC#1]
hallo, ich hab es nachgebaut und funktioniert super.
Danke für deine suuuper Arbeit.
ich will der HB-UNI-Sen-RFID-RC als Zugangskontrolle für mein Gartenhaus nutzen und um die Tür zu entsperren muss ein Relais aktiviert werden, gibt es die Möglichkeit die freien IO PIN am Arduino für die Relais Steuerung zu nutzen , es wäre super wenn man mit Mithilfe von SUBMIT-Commands die restlichen IO Pins des Arduino's steuern kann, dann kann man damit viele Sachen machen

**Comment by jp112sdl** [comment]
Hi,

das ist ein bisschen viel Aufwand.
Man müsste noch SwitchChannel implementieren und diese dann intern mit den RemoteChannels verknüpfen.
Soweit noch nicht wirklich dramatisch, aber das Ganz dann auch auf der CCU einzubauen ist mit viel Arbeit verbunden.

Es ist daher einfacher, du nimmst einen 2. Pro Mini als Aktor-Device, und verknüpfst diesen direkt mit dem RFID-RC.

**Comment by sikousikou** [comment]
Danke,
werde mir dann ein Pro Mini und cc1101 bestellen.
