### ISSUE TITLE
Verwendung von einem RDM6300 möglich?

### ISSUE THREAD

**Issue by fraeggle** [jp112sdl/HB-UNI-Sen-RFID-RC#3]
Hi. Ich habe ein RDM6300 Modul. Ist es möglich dies auch zu verwenden?

Gruß Peter

**Comment by jp112sdl** [comment]
Hi,

nein der wird nicht untersützt. 
Ist auch kurz-/mittelfristig nicht geplant

**Comment by fraeggle** [comment]
Danke für die Info.
Schade  

Gruß Peter

**Comment by jp112sdl** [comment]
Ich hab tatsächlich noch einen RDM6300 in meiner Kramkiste gefunden.
Werd morgen mal schauen, ob der unkompliziert einzubinden geht.

**Comment by jp112sdl** [comment]
@fraeggle Ich habe da mal was zusammengebaut.
Du brauchst 
- die .ino hier aus dem dev_rdm6300 Branch: 
https://github.com/jp112sdl/HB-UNI-Sen-RFID-RC/blob/dev_rdm6300/HB-UNI-Sen-RFID-RC.ino
- die RFID.h aus der AskSinPP-Lib dev_rdm6300 Branch:
https://github.com/jp112sdl/AskSinPP/blob/dev_rdm6300/RFID.h

Im Sketch Zeile 21 kommentieren (//) sowie Zeile 23 "entkommentieren".

Der TX Pin vom RDM6300 wird an Pin 3 des Pro Mini angeschlossen.
https://github.com/jp112sdl/HB-UNI-Sen-RFID-RC/blob/dev_rdm6300/HB-UNI-Sen-RFID-RC.ino#L69

Bitte mal testen. Der RDM6300 ist aufgrund seiner trägen Übertragung etwas unhandlich, finde ich.

**Comment by fraeggle** [comment]
:-O  :-D  Klaro  dauert aber.. hab erst am WE Zeit.. aber ich geb dir auf alle Fälle Rückmeldung.
Die RFID.h müsste ich ja schon haben. Verwende Atom (Platformio) und da hab ich die AskSinPP  drin
Gruß Peter

**Comment by jp112sdl** [comment]
> Die RFID.h müsste ich ja schon haben

aber nicht **[diese](https://github.com/jp112sdl/AskSinPP/blob/dev_rdm6300/RFID.h)**.
Da sind auch Änderungen drin

**Comment by fraeggle** [comment]
dacht ich mir  ;-) nachdem ich gesehen hab dass die anderes Datum und Größe hat.
Also die Geschwindigkeit an sich ist noch ok. Der ESP den ich im Moment verwende ist nicht viel schneller. Nur möcht ich halt gern weg von WLAN.
Hab zur Sicherheit auch nen Spg Teiler am Pin 3 da ich mir nicht sicher bin wieviel Volt Eingang der Mini verträgt.
Seh ich das richtig, das man 8 ID einlernen kann? Das wär etwas zu wenig (für mich) aber ansonsten SUPER ARBEIT. FUNKTIONIERT  :-D

![image](https://user-images.githubusercontent.com/40692505/84270200-a006d580-ab2a-11ea-95f2-1624aad8b5de.png)

**Comment by jp112sdl** [comment]
> Hab zur Sicherheit auch nen Spg Teiler am Pin 3 da ich mir nicht sicher bin wieviel Volt Eingang der Mini verträgt.

Ja, das ist ne gute Idee. Du versorgst den RDM6300 mit **5V**?
Ich hab bei meinem Testaufbau den LDO gebrückt und ihn direkt an 3.3V angeschlossen. Dann stimmt auch der Pegel.
Wobei ich nicht mal glaube, dass bei 5V-Versorgung der TX-Level auch 5V ist. Denn die Schaltung wird ja vom LDO nur mit 3.3V versorgt!?

Wie auch immer - hauptsache es geht :)

Wenn du mehr Kanäle benötigst, kannst du [`#define NUM_CHANNELS          8`](https://github.com/jp112sdl/HB-UNI-Sen-RFID-RC/blob/a14ad63df1ee83216884a5eeeb16cadb56555234/HB-UNI-Sen-RFID-RC.ino#L57) erhöhen.

Musst nur mal schauen, was beim Starten im seriellen Monitor bei `Address Space 32-xxx` ausgegeben wird.
Darf nicht mehr als 1024 sein.

**Comment by jp112sdl** [comment]
P.S.: Die Änderungen sind jetzt überall im master-Branch drin

**Comment by fraeggle** [comment]
Du bist super....
Zur Info..  
Wenn du den RDM mit "nur" 3V3 versorgst, verringert sich tatsächlich die Reichweite. Bei mir um Signifikante 2 - 3 cm. Je nach verwendetem Transponder (Karte,Anhänger...) Wobei Karten die größte Reichweite haben.
16 Kanäle ergeben Address Space 32-916.......

Danke Dir nochmal....
Von mir aus kannst du das zu machen  ;-)
Gruß Peter

**Comment by jp112sdl** [comment]
> Wenn du den RDM mit "nur" 3V3 versorgst, verringert sich tatsächlich die Reichweite.

Gut zu wissen, danke für die Rückmeldung!

**Comment by akula3** [comment]
Hallo,
ich bekomme beim kompilieren mit dem Arduino IDE die Fehlermeldung:

Arduino: 1.8.13 (Windows 10), Board: "Arduino Mini, ATmega328P"

HB-UNI-Sen-RFID-RC:253:67: error: could not convert template argument 'readerDevice' from 'SoftwareSerial' to 'MFRC522&'

 RFIDScanner<RFIDDev, RfidChannel, readerDevice, LED2_PIN, LED1_PIN> scanner(sdev);

                                                                   ^

HB-UNI-Sen-RFID-RC:253:81: error: cannot convert 'RFIDDev' to 'int' in initialization

 RFIDScanner<RFIDDev, RfidChannel, readerDevice, LED2_PIN, LED1_PIN> scanner(sdev);

                                                                                 ^

D:\! My Projects\HomeMatic\RFID-Reader als Sender (Tasterschnittstelle)\HB-UNI-Sen-RFID-RC\HB-UNI-Sen-RFID-RC.ino: In function 'void setup()':

HB-UNI-Sen-RFID-RC:268:23: error: cannot allocate an object of abstract type 'as::Alarm'

   sysclock.add(scanner);

                       ^

In file included from C:\Users\kon-s\Documents\Arduino\libraries\AskSinPP-4/Pins.h:6:0,

                 from C:\Users\kon-s\Documents\Arduino\libraries\AskSinPP-4/AskSinPP.h:41,

                 from D:\! My Projects\HomeMatic\RFID-Reader als Sender (Tasterschnittstelle)\HB-UNI-Sen-RFID-RC\HB-UNI-Sen-RFID-RC.ino:57:

C:\Users\kon-s\Documents\Arduino\libraries\AskSinPP-4/Alarm.h:15:7: note:   because the following virtual functions are pure within 'as::Alarm':

 class Alarm: public Link {

       ^~~~~

C:\Users\kon-s\Documents\Arduino\libraries\AskSinPP-4/Alarm.h:23:16: note: 	virtual void as::Alarm::trigger(as::AlarmClock&)

   virtual void trigger(AlarmClock&) = 0;

                ^~~~~~~

exit status 1

could not convert template argument 'readerDevice' from 'SoftwareSerial' to 'MFRC522&'


Liegt das eventuell auch an [RFID.h](https://github.com/jp112sdl/HB-UNI-Sen-RFID-RC/issues/3#issuecomment-641415325)?

**Comment by akula3** [comment]
Hallo Jérôme,
mein RDM6300 funktioniert soweit, AES, Programme, direkte Verknüpfungen, Token anlernen und löschen - alles geht.
Nun wollte ich die gespeicherte Chip-ID, die in der WebUI sichtbar ist, mit der auf dem Token aufgedruckten vergleichen.
Mir ist aufgefallen, dass in der WebUI ein Byte fehlt bzw. ist verschoben.
Ein Beispiel:
Ich habe eine Karte mit aufgedruckter ChipID 0004086814. Der RDM6300 liefert 5 Byte an Daten, für die Beispiel Karte es wären 78003E5C1E. Was auch stimmt: DEC 0004086814 = HEX 003E5C1E, das erste Byte soll die Manufacturer ID sein soweit ich weiss.
In der WebUI sehe ich für diese Karte 07080000030E050C, was bedeuted, dass der Arduino wertet die ersten 4 Bytes (78003E5C, einzelne digits separiert mit 0) von gelieferten 5 Bytes an Daten aus. Somit sind zwei Token mit ChipID's 000408681**4** und 000408681**5** und gleicher Manufacturer ID für den Arduino und dementsprechend CCU absolut gleich.
Ich habe es mit zwei Tokens aus gleichen Batch ausprobiert, wo die Seriennummern drauffolgend sind (bei einem 2, bei anderem 3 am Ende). Dann habe ich nur den mt Endziffer 2 angelernt, und tatsächlich - die CCU erkennt auch den mit endziffer 3 ohne es angelernt zu haben.
Ist es möglich, dass alle 5 Bytes ausgewertet, abgespeichert und in der WebUI angezeigt werden?

Ich habe in der RFID.h die beiden Zeilen
```
#define   ID_ADDR_SIZE 8
DEFREGISTER(RFIDReg1,CREG_AES_ACTIVE,0xe0,0xe1,0xe2,0xe3,0xe4,0xe5,0xe6,0xe7)
```
auf
```
#define   ID_ADDR_SIZE 10
DEFREGISTER(RFIDReg1,CREG_AES_ACTIVE,0xe0,0xe1,0xe2,0xe3,0xe4,0xe5,0xe6,0xe7,0xe8,0xe9)
```
geändert.
Das hat aber nichts gebracht, ausser die Tokens wurden nicht erkannt, obwohl ich sie angelernt habe.

**Comment by jp112sdl** [comment]
Du musst das hier reparieren:
https://github.com/pa-pa/AskSinPP/blob/master/RFID.h#L382-L399
speziell Zeile 396.

Es wird jedes eingehende Zeichen als einzelner Byte-Wert behandelt. 
Aber das soll ja nur paarweise passieren.

**Comment by jp112sdl** [comment]
Probier mal so
```
   while (rdrDev.available()) {
     char d = rdrDev.read();
     static uint8_t bytecount = 0;
     static uint8_t readcount = 0;
     static uint8_t value = 0;
     switch (d) {
       case 0x02:
         bytecount = 0;
         readcount = 0;
         break;
       case 0x03:
         bytecount = 0;
         readcount = 0;
         while (rdrDev.available()) rdrDev.read(); //empty rx buffer
         return true;
         break;
       default:
         value += (d > 57) ? d -= 55 : d -= 48;
         if (readcount++ % 2 == 0) {
            value *= 0x0f;
         } else {
           if (bytecount < 8) addr[bytecount++] = value;
           value = 0;
         }
       break;
     }
   }
```

**Comment by akula3** [comment]
Es ging somit den Sketch zu kompilieren und ins Arduino laden, die Karten/Tokens werden auch angelernt.
Allerdings sehe ich in der WebUI eine ganz falsche ChipID.
Auch die angelernten Karten/Tokens werden als unbekant gemeldet.

**Comment by akula3** [comment]
Und wenn ich den selben Token an untrschiedliche Kanäle anlerne, dann habe ich immer unterschiedliche Chip ID in der WebUI.
Ich würde erwarten, dass die auch gleich sein sollen.

**Comment by jp112sdl** [comment]
Ja dann ist da noch ein Fehler drin... hab aber nix zum Live Testen hier

**Comment by akula3** [comment]
ich versuche grad den Code zu verstehen. Leider bin ich nicht gut im Programmieren....
Würde gerne testen, wenn Du was probieren möchtest.

**Comment by jp112sdl** [comment]
Ich glaub ich war auf dem Holzweg... der Code hätte eigentlich so funktionieren müssen wie er war. 
Was anderes fällt mir aber auch grad nicht ein.
Schau ich mir die Tage noch mal an wenn ich Zeit hab

**Comment by jp112sdl** [comment]
Probier es mal so
```
   while (rdrDev.available() > 0) {
     char d = rdrDev.read();
     static uint8_t bytecount = 0;
     static bool decode = false;
     switch (d) {
       case 0x02:
         bytecount = 0;
         decode = true;
         break;
       case 0x03:
         decode = false;
         while (rdrDev.available()) rdrDev.read(); //empty rx buffer
         return true;
         break;
       default:
         if (decode == true) {
           if (bytecount > 1) {
           uint8_t val = (d > 57) ? d -= 55 : d -= 48;
           if (bytecount < 10) {
             addr[bytecount-2] =  val;
            }
          }
         bytecount++;
       }
       break;
     }
   }
```

**Comment by akula3** [comment]
Du bist großartig! Es funktioniert jetzt.
Die komplette Seriennummer des Tokens (4 Bytes) wird in der WebUI angezeigt, einzelne Digits mit 0 getrennt.
Die Tokens lassen sich anlernen und tracken.
Es gibt kein Problem mit drauffolgenden Seriennummern.
Fehlt nur noch die führende Manufacturer ID. Das ist ein potenzielles Problem bei Tokens unterschiedlicher Hersteller mit gleicher Seriennummer.
Ist es aufwendig sie einzubauen? - ich werde es auf jeden Fall versuchen.

Vielen Dank!

**Comment by jp112sdl** [comment]
Die Wahrscheinlichkeit, dass du in einem Haushalt oder ein externer Einbrecher ^^ eine zweite identische ChipID nur mit anderem Hersteller-Byte hat, halte ich für äußerst gering.

Aber du kannst es ja versuchen

**Comment by jp112sdl** [comment]
Ich bin gerade mal dazu gekommen, mir einen Testsketch zu installieren, der die Rohdaten des Chips ausgibt.
```
06:58:48.922 ->  1 F 0 0 6 4 4 B B 6 8 6  
06:58:48.922 -> --------
06:58:48.922 -> Message-Head: 2
06:58:48.922 -> Message-Data (HEX): 
06:58:48.922 -> 1F (version)
06:58:48.922 -> 00644BB6 (tag)
06:58:48.922 -> Message-Checksum (HEX): 86
06:58:48.922 -> Message-Tail: 3
06:58:48.922 -> --
06:58:48.922 -> Extracted Tag: 6572982
06:58:48.922 -> Extracted Checksum (HEX): 86 (OK)
```

Demnach sind es ja doch nur 4 Byte der Tag-ID (`00 64 4B B6`) 
Das bietet ja dann noch Platz für die (version) (`1F`) . Das ist wahrscheinlich das, was du als "manufacturer" bezeichnest.

**Comment by akula3** [comment]
> Die Wahrscheinlichkeit, dass du in einem Haushalt oder ein externer Einbrecher ^^ eine zweite identische ChipID nur mit anderem Hersteller-Byte hat, halte ich für äußerst gering.

Du hast ja vollkommen recht. Ich bin einfach ein wenig paranoid :-D
> Das bietet ja dann noch Platz für die (version) (1F) . Das ist wahrscheinlich das, was du als "manufacturer" bezeichnest.

Das kann sein. Ich bin nur der Meinung, irgendwo über Manufacturer ID gelesen zu haben.

**Comment by jp112sdl** [comment]
Also wenn du noch Muße für weitere Spiele hast, dann probier es mal damit:

```
   while (rdrDev.available() > 0) {
     char d = rdrDev.read();
     static uint8_t bytecount = 0;
     static uint8_t addrval = 0;
     static bool decode = false;
     switch (d) {
       case 0x02:
         bytecount = 0;
         memset(addr,0x00,ID_ADDR_SIZE);
         decode = true;
         break;
       case 0x03:
         decode = false;
         DPRINTLN("");
         while (rdrDev.available()) rdrDev.read(); //empty rx buffer
         return true;
         break;
       default:
         if (decode == true) {
           uint8_t val = (d > 57) ? d -= 55 : d -= 48;
           if (bytecount % 2 == 0) {
             addrval = val << 4;
           } else {
             addrval |= val;
             addr[bytecount/2] =  addrval;
             //DPRINT("[");DDEC(bytecount/2);DPRINT("]=");DHEXLN(addrval);
             addrval = 0;
           }
           bytecount++;
         }
         break;
     }
   }
```

Die ID aus meinem Debug-Schnipsel vorhin wird nun komplett mit 6 Bytes übertragen (Hersteller/ID/Checksum).

<img width="169" alt="Bildschirmfoto 2020-10-22 um 07 46 55" src="https://user-images.githubusercontent.com/18190139/96829899-c32b8500-143a-11eb-9262-f4ff55c0842d.png">


Mir ist aufgefallen, dass manchmal serielle Grütze und somit die ID falsch gelesen wird.
Sauber wäre, noch ein Checksum-Verfahren einzubauen. Aber das wird mir grad zu viel Aufwand.

**Comment by akula3** [comment]
Das funktioniert super!
Ein großer Dank an dieser Stelle :-)
Ich würde sagen, das Gerät ist reif für den festen Einbau.

Das mit der Checksumme ist eine sehr gute Idee, auch wenn sie erstmal nicht nachgerechnet wird. Wenn mal beim Anlernen die serielle Grütze vorkommt, dann ist es nicht so schlimm - man testet ja den Token nach dem Anlernen, im schlimmsten Fall noch mal anlernen. Und im Betrieb (wenn der Token korrekt angelernt wurde) kommt höchstens eine Sperre, dann mit dem nächsten Einscannen sollte es funktionieren.
