### ISSUE TITLE
Compilerfehler

### ISSUE THREAD

**Issue by jp112sdl** [jp112sdl/HB-UNI-Sen-RFID-RC#5]
Hallo,
ich bekomme beim kompilieren mit dem Arduino IDE die Fehlermeldung:
```
Arduino: 1.8.13 (Windows 10), Board: "Arduino Mini, ATmega328P"

HB-UNI-Sen-RFID-RC:253:67: error: could not convert template argument 'readerDevice' from 'SoftwareSerial' to 'MFRC522&'

 RFIDScanner<RFIDDev, RfidChannel, readerDevice, LED2_PIN, LED1_PIN> scanner(sdev);

                                                                   ^

HB-UNI-Sen-RFID-RC:253:81: error: cannot convert 'RFIDDev' to 'int' in initialization

 RFIDScanner<RFIDDev, RfidChannel, readerDevice, LED2_PIN, LED1_PIN> scanner(sdev);

                                                                                 ^

D:\! My Projects\HomeMatic\RFID-Reader als Sender (Tasterschnittstelle)\HB-UNI-Sen-RFID-RC\HB-UNI-Sen-RFID-RC.ino: In function 'void setup()':

HB-UNI-Sen-RFID-RC:268:23: error: cannot allocate an object of abstract type 'as::Alarm'

   sysclock.add(scanner);

                       ^

In file included from C:\Users\kon-s\Documents\Arduino\libraries\AskSinPP-4/Pins.h:6:0,

                 from C:\Users\kon-s\Documents\Arduino\libraries\AskSinPP-4/AskSinPP.h:41,

                 from D:\! My Projects\HomeMatic\RFID-Reader als Sender (Tasterschnittstelle)\HB-UNI-Sen-RFID-RC\HB-UNI-Sen-RFID-RC.ino:57:

C:\Users\kon-s\Documents\Arduino\libraries\AskSinPP-4/Alarm.h:15:7: note:   because the following virtual functions are pure within 'as::Alarm':

 class Alarm: public Link {

       ^~~~~

C:\Users\kon-s\Documents\Arduino\libraries\AskSinPP-4/Alarm.h:23:16: note: 	virtual void as::Alarm::trigger(as::AlarmClock&)

   virtual void trigger(AlarmClock&) = 0;

                ^~~~~~~

exit status 1

could not convert template argument 'readerDevice' from 'SoftwareSerial' to 'MFRC522&'
```

Liegt das eventuell auch an [RFID.h](https://github.com/jp112sdl/HB-UNI-Sen-RFID-RC/issues/3#issuecomment-641415325)?

_Originally posted by @akula3 in https://github.com/jp112sdl/HB-UNI-Sen-RFID-RC/issues/3#issuecomment-704317457_

**Comment by jp112sdl** [comment]
Verwendest du die aktuelle AskSinPP-Version aus dem master-Branch?

**Comment by akula3** [comment]
nein, ich habe die v4 wie es in der Beschreibung angeraten ist

**Comment by jp112sdl** [comment]
Okay, ja das sorgt leider manchmal etwas für Verwirrung :/
Probiere bitte mal mit dem master-Branch.

**Comment by akula3** [comment]
jepp, jetzt lässt sich der Sketch kompilieren! Danke für den Hinweis!
Leider komme ich trotzdem nicht weiter und hade nun:
avrdude: stk500_getsync() attempt 1 of 10: not in sync: resp=0x06
avrdude: stk500_getsync() attempt 2 of 10: not in sync: resp=0x98
avrdude: stk500_getsync() attempt 3 of 10: not in sync: resp=0x1e
avrdude: stk500_getsync() attempt 4 of 10: not in sync: resp=0xe6
avrdude: stk500_getsync() attempt 5 of 10: not in sync: resp=0xe6
avrdude: stk500_getsync() attempt 6 of 10: not in sync: resp=0xe6
avrdude: stk500_getsync() attempt 7 of 10: not in sync: resp=0x98
avrdude: stk500_getsync() attempt 8 of 10: not in sync: resp=0x66
avrdude: stk500_getsync() attempt 9 of 10: not in sync: resp=0xe6
avrdude: stk500_getsync() attempt 10 of 10: not in sync: resp=0x86

Versuche grad dazu was rauszufinden, bis jetzt ohne Erfolg.
Den FTDI Adapter habe ich schon immer ohne Probleme benutzt

**Comment by akula3** [comment]
uups! falsches Board in der IDE ausgewählt - deswegen.
Sieht jetzt erstmal gut aus. Werde nun an die CCU anlernen.

Vielen Dank nochmal!
Du kannst den Case schliessen
