### ISSUE TITLE
Protokollieren

### ISSUE THREAD

**Issue by akula3** [jp112sdl/HB-UNI-Sen-RFID-RC#6]
Hallo Jérôme,
das Protokollieren funktioniert nur wenn der Sensor über die WebUI ausgelöst wird.
Die Ereignisse am RFID selber, die durch eine Karte oder Token ausgelöst sind, werden nicht protokolliert.
Ist es so gewollt oder mache ich irgendwo ein Fehler?
Danke und Gruß,
Konstantin

**Comment by jp112sdl** [comment]
> das Protokollieren

Welches Protokollieren? Wo wird was protokolliert?

**Comment by akula3** [comment]
Ich meine Systemprotokoll:
![grafik](https://user-images.githubusercontent.com/58461189/98080892-7c944c80-1e76-11eb-84ed-ee6aa74d42ef.png)

**Comment by jp112sdl** [comment]
Also bei mir kommt das, wenn ich einen Chip kurz vor den Leser:
<img width="946" alt="Bildschirmfoto 2020-11-04 um 09 39 52" src="https://user-images.githubusercontent.com/18190139/98088405-b159d100-1e81-11eb-8c4d-459d3b074970.png">

**Comment by akula3** [comment]
Das habe ich wenn ich über WebUI die Kanäle aktiviere. Wenn ich ein Chip benutze, dann kommt garnichts.
Habe schon versucht, die Protokollierung bei den Kanälen alle einzelnd und alle zusammen deaktivieren und aktivieren - hilft nichts.
Nur von eindemselben der angelernten Chips kommt mit regelmäßigen Abstand von 1 Stunde 9 Sekunden (obwohl er garnicht aktiv war):
![grafik](https://user-images.githubusercontent.com/58461189/98103130-d1df5680-1e94-11eb-8691-516a4c3927fb.png)

**Comment by jp112sdl** [comment]
> Wenn ich ein Chip benutze, dann kommt garnichts. 

Aber in einem Programm funktioniert es (die Chiperkennung kurz/lang)? 


Das Gerät selbst hat nichts, was irgendwie spezifisch auf die Protokollierungsfunktion Einfluss nimmt. Das ist Standard-CCU Funktionalität

**Comment by akula3** [comment]
Ja, die Direktverknüpfung funktioniert wunderbar.
Habe grade ein FW Update von 2.53.27 auf 2.53.34 (die von Gestern) gemacht, hat auch nicht geholfen.
Oder werden die aktivitäten von Direktverbindungen nicht mitprotokolliert?

UND: nach dem FW Update sind alle angelernten Key ID's verschwunden (die Keys funktionieren trotzdem):
![grafik](https://user-images.githubusercontent.com/58461189/98107189-6ef0be00-1e9a-11eb-8aae-254abe127606.png)

**Comment by jp112sdl** [comment]
> Oder werden die aktivitäten von Direktverbindungen nicht mitprotokolliert?

Das weiß ich nicht, da musst du mal im HM Forum fragen. Ich nutze die Protokollierung nur sehr selten.
Vermuten würde ich, dass auch DVs protokolliert werden müssten

> UND: nach dem FW Update sind alle angelernten Key ID's verschwunden (die Keys funktionieren trotzdem):

Die sind nach einem Neustart immer leer, weil die CCU keine Werte von Geräten persistent speichert.
Du kannst die Übertragung der ChipID erzwingen, indem du den Befehl
`dom.GetObject("BidCos-RF.JPRFID0001:1.SUBMIT").State("0xfe");` (z.B. über Skript testen) schickst . 
Muss halt nur für jeden Kanal einzeln erfolgen.

Siehe auch _Erzwingen der Chip ID Übertragung zur CCU_:
https://github.com/jp112sdl/HB-UNI-Sen-RFID-RC#steuerbefehle

**Comment by akula3** [comment]
> _Erzwingen der Chip ID Übertragung zur CCU_:

Aha, jetzt verstehe ich, wozu es da ist :-D
Nun hab ich sie alle!
Leider klappt die Übertragung nicht, wenn sie in einem Batch durchgeführt wird.

Und es ist tatsächlich so, dass die Aktivitäten von DV nicht mitprotokolliert werden, aber die von den Programmen schon.
Werde mal eventuell im Forum nachfragen.

**Comment by jp112sdl** [comment]
> Leider klappt die Übertragung nicht, wenn sie in einem Batch durchgeführt wird.

Ich habe ein Programm mit 8x DANN je 1 Chip und jeweils 10 Sekunden verzögert.
Ist ja nur mal bei einem Neustart von nöten

**Comment by akula3** [comment]
so etwa für 16 Kanäle?
![grafik](https://user-images.githubusercontent.com/58461189/98117720-75873180-1eaa-11eb-89b3-08e8954bc49e.png)

**Comment by jp112sdl** [comment]
Nein, so würden ja alle 16 auf einmal 10 Sekunden nach Programmstart loslaufen. 

Du musst die Abstände schon staffeln
10
20
30
...

**Comment by akula3** [comment]
Oh ja, klar!

**Comment by akula3** [comment]
Irgendwie funktioniert es als Programm bei mir nicht. Wenn ich manuell unter "Skript testen" es mach, dann geht's.
Hast Du eine Idee?
![grafik](https://user-images.githubusercontent.com/58461189/98439107-ad32eb00-20ef-11eb-8182-42f7aac15fcb.png)

**Comment by akula3** [comment]
Dazu folgende Meldungen im Syslog:
```
Nov  7 12:01:24 ccu2 user.err rfd: HSSParameter::SetValue() "0xfe" Put failed
Nov  7 12:01:24 ccu2 local0.warn ReGaHss: WARNING: XMLRPC 'setValue': rpcClient.isFault() failed (url: xmlrpc_bin://127.0.0.1:2001, params: {"JPRFID0001:1","SUBMIT","0xfe"}, result: [faultCode:-1,faultString:"Failure"]) [CallXmlrpcMethod():iseXmlRpc.cpp:2608]
Nov  7 12:01:24 ccu2 local0.err ReGaHss: ERROR: XMLRPC 'setValue' call failed (interface: 1007, params: {"JPRFID0001:1","SUBMIT","0xfe"}) [CallSetValue():iseXmlRpc.cpp:1505]
Nov  7 12:01:24 ccu2 local0.err ReGaHss: ERROR: rpc.CallSetValue failed; address = JPRFID0001:1 [WriteValue():iseDOMdpHSS.cpp:76]
Nov  7 12:01:34 ccu2 user.err rfd: HSSParameter::SetValue() "0xfe" Put failed
Nov  7 12:01:34 ccu2 local0.warn ReGaHss: WARNING: XMLRPC 'setValue': rpcClient.isFault() failed (url: xmlrpc_bin://127.0.0.1:2001, params: {"JPRFID0001:2","SUBMIT","0xfe"}, result: [faultCode:-1,faultString:"Failure"]) [CallXmlrpcMethod():iseXmlRpc.cpp:2608]
Nov  7 12:01:34 ccu2 local0.err ReGaHss: ERROR: XMLRPC 'setValue' call failed (interface: 1007, params: {"JPRFID0001:2","SUBMIT","0xfe"}) [CallSetValue():iseXmlRpc.cpp:1505]
Nov  7 12:01:34 ccu2 local0.err ReGaHss: ERROR: rpc.CallSetValue failed; address = JPRFID0001:2 [WriteValue():iseDOMdpHSS.cpp:76]
Nov  7 12:01:44 ccu2 user.err rfd: HSSParameter::SetValue() "0xfe" Put failed
Nov  7 12:01:44 ccu2 local0.warn ReGaHss: WARNING: XMLRPC 'setValue': rpcClient.isFault() failed (url: xmlrpc_bin://127.0.0.1:2001, params: {"JPRFID0001:3","SUBMIT","0xfe"}, result: [faultCode:-1,faultString:"Failure"]) [CallXmlrpcMethod():iseXmlRpc.cpp:2608]
Nov  7 12:01:44 ccu2 local0.err ReGaHss: ERROR: XMLRPC 'setValue' call failed (interface: 1007, params: {"JPRFID0001:3","SUBMIT","0xfe"}) [CallSetValue():iseXmlRpc.cpp:1505]
Nov  7 12:01:44 ccu2 local0.err ReGaHss: ERROR: rpc.CallSetValue failed; address = JPRFID0001:3 [WriteValue():iseDOMdpHSS.cpp:76]
```

**Comment by jp112sdl** [comment]
Nee keine Ahnung was da anders ist
