### ISSUE TITLE
Anlernen an Raspberrymatic CCU nicht möglich

### ISSUE THREAD

**Issue by jgrabitzky** [jp112sdl/HB-UNI-Sen-RFID-RC#7]
Hallo,
ich bekomme den Aufbau leider nicht an der CCU angelernt.
Verkabelung habe ich mehrfach kontrolliert, ist korrekt.
Im Einsatz habe ich Raspberrymatic in der Version 3.57.4.20210320
Das Addon habe ich installiert und es hat die Version 4.2.
Hier noch ein Auszug aus meinem Monitor in der IDE
```
��������������������������������������������������������������AskSin++ v5.0.0 (Mar 23 2021 12:14:00)
Address Space: 32 - 510
CC init1
CC Version: 04
 - ready
Init MFRC522 Reader... Firmware Version: 0x92
Config Changed List0
Activate Cycle Msg
<- 0E 01 86 10 F33C00 000000 06 02 00 00 00  - 116
ignore 0C 32 84 70 6AF16D 000000 00 EA 23  - 3201
ignore 0C 36 86 5A 6AF3E2 000000 88 E6 21  - 3246
 debounce
 pressed
 released
<- 1A 02 84 00 F33C00 000000 10 F3 3C 4A 50 52 46 49 44 30 30 30 31 40 08 00 00  - 22906

ignore 0C 36 84 70 6AF3E2 000000 00 E6 21  - 23136
ignore 0D 02 80 41 6AF16D 709E66 07 5C 00 80  - 31637
ignore 0E 11 B0 11 6D014C 709E66 02 02 00 00 00  - 31991
ignore 0E 11 80 02 709E66 6D014C 01 02 00 00 00  - 32137
ignore 0E 1A B0 11 6D014C 709E66 02 01 00 00 00  - 53172
ignore 0E 1A 80 02 709E66 6D014C 01 01 00 00 00  - 53299
ignore 0D 02 80 41 6AF3E2 70D49F 07 22 00 80  - 69853
ignore 0D 02 80 41 6AF3E2 70D49F 07 22 00 80  - 70137
```` 

Für Hilfe währe ich dankbar.

**Comment by jp112sdl** [comment]
Bitte FreqTest ausführen
- https://asksinpp.de/Grundlagen/FAQ/Fehlerhafte_CC1101.html
- https://homematic-forum.de/forum/viewtopic.php?f=76&t=63125&p=649446#p648640

**Comment by jgrabitzky** [comment]
Hallo,
vielen Dank für die Hilfe.
Ich habe den Frequenztest jetzt mal ausgeführt wie Punkt 1 beschrieben und die Daten angepasst.
Erkannt wird es jetzt und die RFID codes können auch angepasst werden.
Leider kann die CCU die Daten nicht übertragen um die config auf auf das Gerät zu senden.

**Comment by jp112sdl** [comment]
Auch nicht wenn du noch mal kurz den Configtaster drückst?

**Comment by jgrabitzky** [comment]
So, ich hab es jetzt nach vielen Versuchen zum laufen. Hab es den ganzen Vormittag laufen lassen und plötzlich war er im Posteingang. Keine Meldungen mehr wenn die Config geschrieben wird.
Auch die Verknüpfung mit einem HM-MOD-Re-8 ist erfolgreich. Jetzt muss ich noch irgendwie den ID Chip anlernen.

**Comment by jp112sdl** [comment]
Den Schalter "Aktiv" neben "Anlernmodus" anklicken, dann Chip gegenhalten

**Comment by jgrabitzky** [comment]
War auch mein Gedanke. Der Chip wird aber nicht erkannt. Die Grüne Lampe geht aus wenn der Chip angelegt wird, weiterhin passiert aber nichts.

**Comment by jgrabitzky** [comment]
Keine Ahnung warum, aber ich habe den EEPROM des Mini gelöscht und den Sketch noch mal runtergeladen und Übertragen. 
Jetzt geht's.

Aber vielen Dank für die Hilfe.

**Comment by jp112sdl** [comment]
Prima!
