### ISSUE TITLE
Batteriespannung anzeigen

### ISSUE THREAD

**Issue by RasputinBerry** [jp112sdl/HB-UNI-Sen-RFID-RC#9]
Hallo Jérôme,

kannst Du noch, falls einfach möglich, einen Kanal für die Batteriespannung in den Sketch einarbeiten ?

Danke für die Antwort.

**Comment by jp112sdl** [comment]
Hi,
nein ist nicht vorgesehen. Das Gerät (und der Sketch) ist nicht für Batteriebetrieb konzipiert

**Comment by RasputinBerry** [comment]
Schade, aber Danke für die schnelle Antwort.
